### ISSUE TITLE
This plugin don't work with pascal compliler

### ISSUE THREAD

**Issue by ZoloZiak** [bblanchon/SublimeText-HighlightBuildErrors#11]
When I try to use your plugin with free Pascal compiler it doesn't mark the wrong lines. I have attached screenshot below:
![image](https://cloud.githubusercontent.com/assets/8522518/10700772/475def36-79c0-11e5-830e-3f2c3bd926a1.png)

**Comment by bblanchon** [comment]
Did you configure the `file_regex` properly?
http://sublimetext.info/docs/en/reference/build_systems.html

**Comment by ZoloZiak** [comment]
![image](https://cloud.githubusercontent.com/assets/8522518/10702246/c1ed5586-79c8-11e5-8838-ea53682784a7.png)

**Comment by bblanchon** [comment]
Does it jump to the error line when you press F4?

**Comment by ZoloZiak** [comment]
Yes, you can see it on first picture.

**Comment by bblanchon** [comment]
Can you check the console?

**Comment by ZoloZiak** [comment]
![image](https://cloud.githubusercontent.com/assets/8522518/10702332/583c9e8e-79c9-11e5-8721-390d31e9f14c.png)

**Comment by ZoloZiak** [comment]
yeah i forgot to show console :D

**Comment by bblanchon** [comment]
You have to remove the capture of `(Error|Fatal)`.

**Comment by ZoloZiak** [comment]
Dont work again... I tryed reinstall sublime text, now f4 dont highlight text... I really dont know where is problem...
![image](https://cloud.githubusercontent.com/assets/8522518/10704180/53742802-79d5-11e5-90eb-a45a99a252c2.png)
![image](https://cloud.githubusercontent.com/assets/8522518/10704186/63089b90-79d5-11e5-88bb-da6c4e7a6339.png)
![image](https://cloud.githubusercontent.com/assets/8522518/10704214/97b863a2-79d5-11e5-9211-291893576805.png)

**Comment by ZoloZiak** [comment]
F4 work when I keep (Error|Fatal)...

**Comment by ZoloZiak** [comment]
So: I deleted that "if" statement in your python code - line 141, it works now:
![image](https://cloud.githubusercontent.com/assets/8522518/10704705/ee4701b2-79d8-11e5-9b6c-d4a93636f744.png)

**Comment by bblanchon** [comment]
The right way of fixing this issue was to correct you file_regex.
You just have to replace `(Error|Fatal)` by `(?:Error|Fatal)`

**Comment by ZoloZiak** [comment]
Ok so my fault. Sorry and thanks for fixing my issue.

**Comment by ZoloZiak** [comment]
Thanks a ton for helping me solve this issue.

**Comment by ZoloZiak** [comment]
I want to thank you a lot for making this. It's helped me a lot in my work and made it so much easier. It's an awesome plugin. I hope you continue your work and keep making stuff like this. ;)

**Comment by bblanchon** [comment]
You're welcome.
Thanks for using my plugin.

A quick suggestion...
You should copy/paste the text instead of making screenshots.
It allows others to copy part of the text and reuse it in their messages.
It's also more friendly with search engines.

**Comment by ZoloZiak** [comment]
Okay I'll keep that in mind the next time. Never thought about it from that perspective. 

Also if you don't mind I wanted to ask one more thing of you.
Do you use stino plugin? If yes, does your plugin work with it ?

Thanks

**Comment by bblanchon** [comment]
No, even though I am a big Arduino fan, I don't use Stino.
