### ISSUE TITLE
Show error message

### ISSUE THREAD

**Issue by Hoten** [bblanchon/SublimeText-HighlightBuildErrors#13]
Seeing the error message would be a huge benefit. But, what would be the best way? Tooltip? Message in the status bar (on the bottom of the screen)?

**Comment by bblanchon** [comment]
A tooltip would be the best, but I'm not sure it's possible with the SublimeText API.

**Comment by Hoten** [comment]
Found this: https://forum.sublimetext.com/t/dev-build-3070/14538

Unless you beat me to it, I'll try it out sometime this weekend.

**Comment by bblanchon** [comment]
It's fine with me. It's unlikely that's find the time to do that in the comings months.
Please make a pull request.

**Comment by bblanchon** [comment]
Implemented in PR #14.
