### ISSUE TITLE
MSVC 2015 compatibility issue

### ISSUE THREAD

**Issue by Uptown76** [bblanchon/SublimeText-HighlightBuildErrors#22]
There are no highlighting of errors from msvc 2015. I'm assuming the output from cl.exe has changed and the parser from highlight build errors plugin is not picking up the errors.

Sample error message:

cl /MD /nologo /Gm- /GR- /EHa- /Od /Oi /WX /W4 /FC /Z7 /TC /c src/main.c /Fo: bin/main.o
main.c
v:\src\main.c(54): error C2065: 'ss': undeclared identifier
v:\src\main.c(54): error C2146: syntax error: missing ';' before identifier 'glfwMakeContextCurrent'
make: *** [bin/main.o] Error 2

I'm assuming the "main.c" line is a new addition to the output. MSVC will group errors under each source file. I don't think previous versions did this. Not sure.

The sublime text build functionality also does not pick up the errors. Pressing f4 or double clicking on the error will not goto the error in the source code.

Thanks

**Comment by bblanchon** [comment]
You probably need to change the `file_regex` of your build system.

It should be something like:

    "file_regex": "(.*)\\((\\d+)\\)\\s*:\\s*(.*)$"

What do you have right now ?

**Comment by Uptown76** [comment]
I'm using the default make build system. It has:

```javascript
"file_regex": "^(..[^:\n]*):([0-9]+):?([0-9]+)?:? (.*)$"
```

I changed to your expression and it seems to be working now. 

Thanks, appreciate it.

**Comment by Uptown76** [comment]
The following section of the expression in the default Make build system

:([0-9]+):?([0-9]+)?:?

is specific to gcc and clang error output formats.

**Comment by bblanchon** [comment]
You're welcome !
