### ISSUE TITLE
Carret disappears in highlighted line

### ISSUE THREAD

**Issue by StJohn3D** [bblanchon/SublimeText-HighlightBuildErrors#4]
I'm using the solarizedToggle sublime package and in dark mode, the carrot/curser is the same color as the highlight color. And so effectively disappears. Now in the Solarized Light mode I can see the carrot just fine.

I think the carrot and build error colors are switching based on the theme. So I could try to track down the theme files and mess with them there.

But what I think would be a far better solution would to simply have a package setting where users can define their own custom build error highlight color.

**Comment by bblanchon** [comment]
OK, I'll add a package setting as soon as I can.

**Comment by bblanchon** [comment]
I added a setting file.
For now the only setting if "error_color".
The plugin should update automatically to version 1.2.0 through Package Control.

**Comment by StJohn3D** [comment]
Thanks! Package Control isn't showing any available updates yet. I'll check again later and try it out.
